### ISSUE TITLE
XmlException: For security reasons DTD is prohibited in this XML document

### ISSUE THREAD

**Issue by nicolas-raoul** [OpenDataSpace/chemistry-dotcmis#3]
Hello OpenDataSpace!

We are using your DotCMIS fork in CmisSync with a lot of different CMIS server, and we have noticed this problem with Documentum and SharePoint servers: https://github.com/aegif/CmisSync/issues/540

A solution to this exception is described here: http://stackoverflow.com/a/28459398/226958

We implemented this solution (minus the DDOS protection a client-side library is probably not a recipient of DDOS attacks) in this commit: https://github.com/aegif/chemistry-dotcmis/commit/ee7e5931b8c8cdfcbbd280a1fb4956a8fcc895b8

Even if this problem does not happen with OpenDataSpace, you might want to merge it to make the OpenDataSpace/chemistry-dotcmis library more attractive to other developers :-)

Cheers!
Nicolas

**Comment by soneyworld** [comment]
Hi Nicolas!
Thanks a lot for that hint! I merged and pushed it into our repository.
Best regards
Till
